name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cirruslabs/flutter:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Flutter
        run: |
          flutter --version
          dart --version

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
